version: "3.3"

services:
  db:
    image: postgres
    container_name: "${COMPOSE_PROJECT_NAME}"
    ports: 
      - "${HOST_PORT}:5432"
    env_file:
      - .env
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}