version: "3"

services:
    webservice:
        build: .
        ports:
            - 9000:5000
        volumes:
            - ./:/app
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
    postgres_data:
